In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

# Review

In [9]:
cones = Table.read_table('lec03/cones.csv')
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

### Discussion Q1

In [4]:
# Find percentage of rows that match the condition color pink

In [10]:
pink_cones = cones.where('Color', 'pink')
pink_cones

Flavor     | Color | Price
strawberry | pink  | 3.55
strawberry | pink  | 5.25
bubblegum  | pink  | 4.75

In [11]:
pink_cones.num_rows / cones.num_rows * 100

50.0

### Discussion Question 2

What does the following evaluate to

```
x = 5
y = 7

max(x, y)
min(x-y, x+y, x*y, x/y)
round(x/y)
x * 2.5
y + '5'

```

In [12]:
x = 5
y = 7

In [13]:
# Case 1
max(x, y)

7

In [14]:
# Case 2
min(x-y, x+y, x*y, x/y)

-2

In [15]:
# Case 3
round(x/y)

1

In [16]:
# Case 4
x * 2.5

12.5

In [17]:
# Case 5
y + '5'

TypeError: unsupported operand type(s) for +: 'int' and 'str'

## Numbers ##

In [18]:
3 * 30 # int

90

In [19]:
10 / 3 # float

3.3333333333333335

In [20]:
3 / 3 # float

1.0

In [21]:
10 ** 3 # 10 * 10 * 10 

1000

In [22]:
10 ** 0.5 # float

3.1622776601683795

In [23]:
12345678 ** 890

ValueError: Exceeds the limit (4300 digits) for integer string conversion; use sys.set_int_max_str_digits() to increase the limit

In [24]:
75892745.215489247589274985712 - 75892745.21548925

0.0

In [25]:
10 / 5

2.0

In [26]:
int(10 / 5)

2

In [27]:
16 / 30

0.5333333333333333

In [28]:
round(16 / 30), int(16 / 30)

(1, 0)

In [29]:
float(3)

3.0

## Strings ##

In [30]:
'Flavor'

'Flavor'

In [31]:
"Flavor"

'Flavor'

In [32]:
Flavor

NameError: name 'Flavor' is not defined

In [33]:
'straw' + 'berry'

'strawberry'

In [34]:
5 + '5'

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [35]:
5 + int('5')

10

In [36]:
'yelp review: ' + str(10)

'yelp review: 10'

## Arrays ##

In [37]:
my_array = make_array(1, 2, 3)
my_array

array([1, 2, 3])

In [38]:
type(my_array)

numpy.ndarray

In [39]:
len(my_array)

3

In [40]:
my_array + 2

array([3, 4, 5])

In [41]:
my_array

array([1, 2, 3])

In [42]:
my_array_plus_two = my_array + 2
my_array_plus_two

array([3, 4, 5])

In [43]:
my_array * 2

array([2, 4, 6])

In [44]:
my_array = my_array ** 2

In [45]:
my_array_2 = make_array(-1, -2, -1)
my_array_2

array([-1, -2, -1])

In [46]:
my_array_2 + my_array

array([0, 2, 8])

In [47]:
my_array_3 = make_array(1,2,3,4)
my_array_3

array([1, 2, 3, 4])

In [48]:
my_array + my_array_3

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [49]:
names_array = make_array('Andrew', 'Conan', 'Jonathan')
names_array

array(['Andrew', 'Conan', 'Jonathan'],
      dtype='<U8')

In [50]:
names_array.item(0)

'Andrew'

In [51]:
names_array.item(1)

'Conan'

In [52]:
names_array.item(3)

IndexError: index 3 is out of bounds for axis 0 with size 3

In [1]:
'this cell will get deleted'

'this cell will get deleted'